blank_issues_enabled: false
contact_links:
  - name: Documentation in Chinese (中文文档)
    url: https://github.com/Robert-Stackflow/better-rss-for-zotero#readme
    about: 如果你是中文用户，请先阅读中文文档。文档中已经说明的问题不会回复。
